version: '3'

services:
  db:
    image: mysql
    container_name: db_sezane_test
    restart: always
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sezane
      MYSQL_USER: sezane
      MYSQL_PASSWORD: sezane
    networks:
      - dev

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin_sezane_test
    restart: always
    depends_on:
      - db
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
    networks:
      - dev
  www:
    build: docker
    container_name: www_sezane_test
    ports:
      - "8000:80"
    volumes:
      - ./docker/vhosts:/etc/apache2/sites-enabled
      - ./:/var/www
    networks:
      - dev


networks:
  dev:

volumes:
  db-data: